# Generated by Django 4.1.7 on 2023-02-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='subject',
        ),
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='make',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='model',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='price',
            field=models.CharField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='todo',
            name='year',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
